# Generated by Django 3.2.5 on 2021-07-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenantApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='PropertyName',
            field=models.CharField(default='No Property', max_length=200),
        ),
    ]
