# Generated by Django 3.2.5 on 2021-07-07 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenantApp', '0002_landlord_propertyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='PropertyName',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='tenantApp.landlord'),
        ),
    ]
